# Zabbix多实例配置文件
instances:
  # 生产环境Zabbix实例
  - name: "xx"
    url: "https:/xxxx/api_jsonrpc.php"
    auth_type: "token"
    token: "bxxxx4"
  # 测试环境Zabbix实例
  - name: "xxxx"
    url: "http://xxxx/api_jsonrpc.php"
    auth_type: "password"
    username: "xxxxxx"
    password: "-xxxxx"
